### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by michael-morningstar** [HackerExperience/legacy#4]
I'm sorry. I'm a little bit confuse when install this on my machine. Can anyone make install guide please

**Comment by augustresende** [comment]
Currently a install guide doesn't exists.

**Comment by michael-morningstar** [comment]
God, i realy need to install this. Ok one question. I already configure database connection and grant permission on the directory. But when i open it in browser , it says "HTTP ERROR 500". How to solve this ?

**Comment by augustresende** [comment]
Enable php errors in php.ini or .htaccess

**Comment by michael-morningstar** [comment]
wow thanks its work.
thank u very much
